name: CI Pipeline

env:
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

# Run on pushes or pull requests to any branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions: read-all  # Added permissions block to restrict to read-only access

jobs:
  pre-commit-and-opentofu-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install shellcheck and unzip
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y shellcheck unzip
          # Downloads the CLI based on your OS/arch and puts it in /usr/local/bin
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost --version

      - name: Install Homebrew (no sudo, install in runner home directory)
        run: |
          # Install Homebrew under the current user (runner)
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # Add Homebrew to PATH for future steps
          echo 'eval "$(/home/runner/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/runner/.linuxbrew/bin/brew shellenv)"

      - name: Install tenv using Homebrew
        run: |
          # Install tenv using Homebrew
          brew install tenv

      - name: Install Terraform 1.5.7 using tenv
        run: |
          # Install and use Terraform 1.5.7 using tenv
          tenv terraform install 1.5.7
          tenv terraform use 1.5.7
          terraform -v

      - name: Install OpenTofu 1.8.3 using tenv
        run: |
          # Install and use OpenTofu 1.8.3 using tenv
          tenv opentofu install 1.8.3
          tenv opentofu use 1.8.3
          opentofu version

      - name: Initialize OpenTofu
        run: opentofu init -input=false

      - name: Run pre-commit hooks
        run: pre-commit run -a

      - name: Run OpenTofu tests
        run: opentofu test
